Record example of minitar not being able to unpack tars built by minitar
```
david@zion:~/git/puppet-modulebuilder (support-long-filenames)$ bundle exec puppet module install --force --ignore-dependencies --target-dir /tmp/d20210211-342731-1gxs8co --verbose /tmp/d20210211-342731-1a9zcwo/pkg/puppetlabs-motd-4.3.0.tar.gz --trace
Notice: Preparing to install into /tmp/d20210211-342731-1gxs8co ...
Error: "/1234567890" is not a valid octal string
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/posix_header.rb:127:in `strict_oct'
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/posix_header.rb:87:in `from_data'
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/posix_header.rb:70:in `from_stream'
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/reader.rb:233:in `block in each_entry'
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/reader.rb:222:in `loop'
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/reader.rb:222:in `each_entry'
/home/david/gems/ruby/2.7.0/gems/minitar-0.9/lib/archive/tar/minitar/input.rb:93:in `each_entry'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/tar/mini.rb:94:in `collect'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/tar/mini.rb:94:in `find_valid_files'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/tar/mini.rb:9:in `block in unpack'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/tar/mini.rb:3:in `open'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/tar/mini.rb:3:in `unpack'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/unpacker.rb:56:in `unpack'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/unpacker.rb:11:in `unpack'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/local_tarball.rb:84:in `unpack'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/local_tarball.rb:12:in `initialize'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/installer.rb:245:in `new'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/installer.rb:245:in `local_tarball_source'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/installer.rb:36:in `initialize'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/application.rb:11:in `new'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/module_tool/applications/application.rb:11:in `run'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/face/module/install.rb:128:in `block (3 levels) in <top (required)>'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/interface/action.rb+eval[wrapper]:261:in `install'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/application/face_base.rb:254:in `main'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/application.rb:437:in `run_command'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/application.rb:421:in `block in run'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/util.rb:735:in `exit_on_fail'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/application.rb:421:in `run'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/util/command_line.rb:143:in `run'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/lib/puppet/util/command_line.rb:77:in `execute'
/home/david/gems/ruby/2.7.0/gems/puppet-7.4.0/bin/puppet:5:in `<top (required)>'
/home/david/gems/ruby/2.7.0/bin/puppet:23:in `load'
/home/david/gems/ruby/2.7.0/bin/puppet:23:in `<main>'
Error: Try 'puppet help module install' for usage
david@zion:~/git/puppet-modulebuilder (support-long-filenames)$ bundle info minitar
  * minitar (0.9)
	Summary: The minitar library is a pure-Ruby library that provides the ability to deal with POSIX tar(1) archive files
	Homepage: https://github.com/halostatue/minitar/
	Path: /home/david/gems/ruby/2.7.0/gems/minitar-0.9
david@zion:~/git/puppet-modulebuilder (support-long-filenames)$
```